---
# @file docker-compose.yml
# @brief Run portainer with a default configuration.
#
# @description This ``portainer`` Docker stack starts a link:https://github.com/portainer/portainer[Portainer CE]
# instance. This link:https://docs.portainer.io[Portainer] instance is pre-configured with an
# admin user and handles deployments of other Docker stacks through GitOps techniques.
#
# | Component     | Port | URL                   |
# | ------------- | ---- | --------------------- |
# | Portainer     | 9990 | http://localhost:9990 |
#
# Additionally a `postman/newman` container is started to initialize portainer with all relevant
# settings. This container runs a Postman collection that sets up all Docker stacks (among other
# things) and runs some tests on the portainer instance. This container is terminated after the
# collecetion run ended.

version: "3.3"
services:

  portainer:
    image: portainer/portainer-ce:2.19.4-alpine
    container_name: portainer
    command: --host unix:///var/run/docker.sock --admin-password-file /tmp/portainer_passwords
    restart: always
    ports:
      - 9990:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - ./assets/portainer.passwd:/tmp/portainer_passwords
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:9000 || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  newman:
    image: postman/newman:6.0.0-alpine
    container_name: newman
    depends_on:
      portainer:
        condition: service_healthy
    volumes:
      - ./assets/collections:/etc/newman
    command: run portainer-postman-collection.json

volumes:
  portainer_data:
