---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: src/main/github
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: src/main/homelab/conky/from-github
    schedule:
      interval: weekly
