---
ls:
  .adoc: kebab-case | SCREAMING_SNAKE_CASE | PascalCase
  .puml: kebab-case
  .md: kebab-case | SCREAMING_SNAKE_CASE

  .conf: kebab-case
  .go: snake_case
  .json: kebab-case
  .rb: kebab-case
  .tf: kebab-case
  .yml: kebab-case
  .yaml: kebab-case | PascalCase # Helm Chart
  .feature: kebab-case # cucumber

  .sh: kebab-case

  .css: kebab-case
  .html: kebab-case
  .js: kebab-case
  .hbs: kebab-case
  .svg: kebab-case

  Dockerfile: PascalCase
  Vagrantfile: PascalCase
  Jenkinsfile: PascalCase

  .env: lowercase
  .folderslintrc: lowercase
  .shellcheckrc: lowercase
  .gitignore: lowercase
  .gitkeep: lowercase

ignore:
  # globals
  - .git
  - .idea
  - .vscode
  - node_modules
  - .gitpod.yml
  - target

  # Helm expects this specific filename in this specific case
  - Chart.yaml

  # linter definitions
  - .ansible-lint.yml
  - .ls-lint.yml
  - .pre-commit-config.yaml
  - .releaserc
  - .yamllint.yml

  # misc
  - src/main/github/.terraform-docs.yml
  - components/homelab/target
  - components/homelab/src/main/docker-stacks/pihole/etc-pihole
  - components/homelab/src/main/docker-stacks/pihole/etc-dnsmasq.d
