---
extends: default

# Helm charts are excluded because they are validated with helm lint
ignore: |
  node_modules
  .vagrant
  target
  components/homelab/src/main/minikube/krokidile-chart/krokidile

rules:
  line-length:
    level: warning
    max: 100
    allow-non-breakable-inline-mappings: true
  new-lines:
    type: unix
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  comments:
    min-spaces-from-content: 1
