---
# @file desktops-main.yml
# @brief Install and configure Ubuntu Desktop workstations.
#
# @description This Ansible playbook is specifically designed to set up all the
# workstations in my  homelab environment. The term "workstations" revers to all
# link:https://ubuntu.com/download/desktop[Ubuntu Desktop] machines used for daily
# business and development.
#
# The purpose of this Ansible playbook is to automate the setup and configuration of
# Ubuntu desktop machines used for daily business and development tasks in my homelab.
# It ensures that these machines are equipped with all the necessary software,
# configurations, and development tools required for efficient work.
#
# * The playbook includes configurations for setting up user accounts, defining user permissions, and configuring user-specific settings like ``.bashrc`` settings and SSH keys.
# * The playbook installs all the needed software required for daily business and development tasks.
# * The playbook installs a comprehensive set of development tools necessary for software development.
#
# This Ansible playbook streamlines the process of setting up Ubuntu desktop workstations
# for personal, business and development purposes, ensuring that they are equipped with the
# necessary software, configurations, and development tools. Additionally, it provides a
# version-controlled and easily reproducible way to maintain my  homelab environment,
# ensuring that all workstations are always up-to-date and configured according to
# specifications.
#
# == Prerequisites
#
# The ``xref:AUTO-GENERATED:src/main/homelab/ansible-cli-sh.adoc[src/main/homelab/ansible-cli.sh]``
# script, which takes care of running this playbook, expects Docker to be installed. A
# local Ansible installation is not needed. When starting on a fresh system without any
# additional packages installed, start with the ``* xref:AUTO-GENERATED:src/main/homelab/bootstrap/install-basics-sh.adoc[src/main/homelab/bootstrap/install-basics.sh]``
# script to make sure all requirements are met.

- name: Setup for group ubuntu_desktop
  hosts: ubuntu_desktop
  gather_facts: true
  become: true
  vars_files:
    - ../vars/global.yml
  tasks:

    - ansible.builtin.import_tasks: ../tasks/common-config-bash-prompt.yml
    - ansible.builtin.import_tasks: ../tasks/common-config-bash-aliases.yml
    - ansible.builtin.import_tasks: ../tasks/ubuntu-desktop-config-bash-aliases.yml
    - ansible.builtin.import_tasks: ../tasks/common-config-create-directories.yml
    - ansible.builtin.import_tasks: ../tasks/common-config-git.yml
    - ansible.builtin.import_tasks: ../tasks/common-install-packages.yml
    - ansible.builtin.import_tasks: ../tasks/ubuntu-desktop-install-packages.yml
    - ansible.builtin.import_tasks: ../tasks/ubuntu-desktop-install-chrome.yml
    - ansible.builtin.import_tasks: ../tasks/ubuntu-desktop-install-media-players.yml
    - ansible.builtin.import_tasks: ../tasks/ubuntu-desktop-uninstall.yml
    - ansible.builtin.import_tasks: ../tasks/common-config-ssh-keypair.yml
    - ansible.builtin.import_tasks: ../tasks/common-install-docker.yml
    - ansible.builtin.import_tasks: ../tasks/ubuntu-desktop-install-ansible.yml
    - ansible.builtin.import_tasks: ../tasks/ubuntu-desktop-install-sublime.yml
    - ansible.builtin.import_tasks: ../tasks/ubuntu-desktop-install-snap-packages.yml
    - ansible.builtin.import_tasks: ../tasks/ubuntu-desktop-install-github-cli.yml
    - ansible.builtin.import_tasks: ../tasks/ubuntu-desktop-install-virtualization.yml
    - ansible.builtin.import_tasks: ../tasks/common-install-docker-wrapper-scripts.yml
    - ansible.builtin.import_tasks: ../tasks/common-install-jarvis.yml

- name: Setup for group ubuntu_desktop (non-root)
  hosts: ubuntu_desktop
  gather_facts: true
  become: false
  vars_files:
    - ../vars/global.yml
  tasks:

    - ansible.builtin.import_tasks: ../tasks/common-config-cron-jobs.yml
    - ansible.builtin.import_tasks: ../tasks/ubuntu-desktop-install-vscode-plugins.yml
    - ansible.builtin.import_tasks: ../tasks/ubuntu-desktop-copy-files.yml

    #  +-----------------------------------------------------------------------------+
    # !|    Must be last task in this play !!!                                       |
    #  |    Local changes result in a failure for this task.                         |
    #  |    In case of failure, all other tasks for the affected node are skipped    |
    #  +-----------------------------------------------------------------------------+
    - ansible.builtin.import_tasks: ../tasks/ubuntu-desktop-clone-repos.yml
