---
- name: Setup for RasPi nodes
  hosts: raspi
  gather_facts: true
  become: true
  vars_files:
    - ../vars/global.yml
  tasks:

    - ansible.builtin.import_tasks: ../tasks/common-config-bash-prompt.yml
    - ansible.builtin.import_tasks: ../tasks/common-config-bash-aliases.yml
    - ansible.builtin.import_tasks: ../tasks/common-config-create-directories.yml
    - ansible.builtin.import_tasks: ../tasks/common-install-packages.yml
    - ansible.builtin.import_tasks: ../tasks/common-config-git.yml

    - ansible.builtin.import_tasks: ../tasks/common-install-docker-wrapper-scripts.yml
    - ansible.builtin.import_tasks: ../tasks/common-install-jarvis.yml

    - name: Config -> Create ssh keypair
      openssh_keypair:
        path: "/home/{{ ansible_user }}/.ssh/id_rsa"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        type: rsa
        size: 4096
        state: present
        force: false

    - ansible.builtin.import_tasks: ../tasks/common-install-docker.yml

    - name: Config -> Clone mandatory git repositories from Github (github.com/sebastian-sommerfeld-io) via https
      ansible.builtin.git:
        repo: "https://github.com/sebastian-sommerfeld-io/{{ item }}.git"
        dest: "/home/{{ ansible_user }}/work/repos/sebastian-sommerfeld-io/{{ item }}"
      with_items:
        - configs
