---
- name: Setup for group x86_ubuntu_desktop
  hosts: x86_ubuntu_desktop
  gather_facts: true
  become: true
  tasks:

    - name: Install -> Steam
      apt:
        pkg:
          - steam
        state: latest
        update_cache: true

    - name: Info -> Post installation message
      debug:
        msg:
          - "Things left to do"
          - "  - Login to Steam (see BitWarden for credentials)"
          - "  - Enable the Steam Beta Client"
          - "    - Go to 'Steam > Settings'"
          - "    - Account tab > click 'change' for Beta Participation  and click on Steam Beta Update"
          - "  - Enable Steam Play for all games"
          - "    - Go to 'Steam > Settings > Steam Play'"
          - "    - Click 'Enable Steam Play for all titles'"
          - "      - Use 'Proton 7.0-6'"
          - "  - Install games"
