---
# @file docker-compose.yml
# @brief Lorem Ipsum ...
#
# @description Lorem Ipsum ...
# TODO ...

version: "3.3"
services:

  website:
    image: sommerfeldio/website:latest
    pull_policy: always
    container_name: website
    restart: unless-stopped
    ports:
      - 8000:80
