---
# @file common-install-jarvis.yml
# @brief Install Jarvis utility.
#
# @description The task installs the link:https://github.com/sebastian-sommerfeld-io/jarvis[Jarvis]
# utility.

- name: Config -> Download jarvis bootstrap script
  ansible.builtin.uri:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/jarvis/install.sh

- name: Config -> Install jarvis from bootstrap script
  ansible.builtin.shell: /tmp/jarvis/install.sh
  args:
    executable: /bin/bash

- name: Install -> Jarvis cleanup
  ansible.builtin.file:
    path: /tmp/chrome.deb
    state: absent
