---
# @file common-git.yml
# @brief Configure Git.
#
# @description The task configures git with the ``.gitconfig`` from this repo.

- name: Config -> Copy git configuration
  ansible.builtin.copy:
    src: ../assets/.gitconfig
    dest: "/home/{{ ansible_user }}/.gitconfig"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "{{ file_permissions }}"
