---
# @file common-uninstall-scripts.yml
# @brief Un-Install old utility scripts.
#
# @description The task un-installs old utility scripts.

- name: Config -> Un-Install old scripts
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/bin/switch-display-inputs
    - /opt/scripts/switch-display-inputs.sh
