---
# @file ubuntu-install-virtualization.yml
# @brief Install Virtualbox and Vagrant with all dependencies.
#
# @description The task installs Virtualbox and Vagrant with some plugins. It also
# adds the ``{{ ansible_user }}`` (which is the user who runs the playbooks, normally ``sebastian``)
# is added to the ``vboxusers`` group to allow running Virtualbox with all features and without
# ``root`` privileges.

- name: Virtualbox Setup -> Install Virtualbox and dependencies
  ansible.builtin.apt:
    pkg:
      - virtualbox
      - virtualbox-qt
      - virtualbox-dkms
    state: latest
    update_cache: true

- name: Virtualbox Setup -> Create virtual machines folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=rx,o=rx
  with_items:
    - "/home/{{ ansible_user }}/virtualmachines"

- name: Virtualbox Setup -> Set virtual machines folder
  ansible.builtin.shell: "vboxmanage setproperty machinefolder /home/{{ ansible_user }}/virtualmachines"
  become_user: "{{ ansible_user }}"
  args:
    executable: /bin/bash

- name: Virtualbox Setup -> Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/bash
    groups: vboxusers
    append: true

- name: Install -> Download Chrome package
  ansible.builtin.uri:
    url: https://releases.hashicorp.com/vagrant/2.2.19/vagrant_2.2.19_x86_64.deb
    dest: /tmp/vagrant.deb
    status_code: [200, 301, 302, 304]

- name: Vagrant Setup -> Install Vagrant
  ansible.builtin.apt:
    deb: /tmp/vagrant.deb

- name: Install -> Vagrant cleanup
  ansible.builtin.file:
    path: /tmp/vagrant.deb
    state: absent

- name: Vagrant Setup -> Install Vagrant plugins
  ansible.builtin.shell: |
    echo "$USER"
    vagrant plugin install vagrant-cachier
    vagrant plugin install vagrant-vbguest
    vagrant plugin install vagrant-docker-compose
  become: true
  become_user: "{{ ansible_user }}"
  args:
    executable: /bin/bash
