---
- name: Install -> Basic packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - ncdu
      - htop
      - git
      - neofetch
      - python3-pip # python package manager
    state: latest
    update_cache: true

- name: Install -> Python packages
  ansible.builtin.pip:
    name: "{{ item }}"
  with_items:
    - pre-commit
