---
- name: Install -> Basic packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - ncdu
      - htop
      - git
      - neofetch
      - python3
    state: latest
    update_cache: true

- name: Install -> Basic packages (python symlink)
  ansible.builtin.file:
    src: "/usr/bin/python"
    dest: "/usr/bin/python3"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
