---
- name: Docker Setup -> Install docker-ce and docker compose
  apt:
    name:
      - docker-ce
      - docker compose
    state: latest
    update_cache: true

- name: Docker Setup -> Add GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker Setup -> Add apt repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Docker Setup -> Install docker-ce and docker compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: Docker Setup -> Add default user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
