---
# @file common-config-bash-prompt.yml
# @brief Update Bash prompt.
#
# @description  The task updates the Bash prompt for the ``{{ ansible_user }}``
# (which is the user who runs the playbooks, normally ``sebastian``).

- name: Config -> Update prompt in .bashrc
  lineinfile:
    dest: "/home/{{ ansible_user }}/.bashrc"
    regexp: '^PS1='
    line: "export PS1='{{ ps1 }}'"
    state: present
