---
- name: Install -> Basic packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - ncdu
      - htop
      - git
      - neofetch
      - python3-pip # python package manager
    state: latest
    update_cache: true
