---
# @file common-config-create-directories.yml
# @brief Setup directory tree.
#
# @description  The task sets up the directory tree and ensures needed all
# folders are present.

- name: Config -> Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=rx,o=rx
  with_items:
    - "/home/{{ ansible_user }}/.config"
    - "/home/{{ ansible_user }}/.config/autostart"
    - "/home/{{ ansible_user }}/work"
    - "/home/{{ ansible_user }}/work/repos"
    - "/home/{{ ansible_user }}/work/repos/sebastian-sommerfeld-io"
    - "/home/{{ ansible_user }}/tmp"
