---
# @file common-install-jarvis.yml
# @brief Install Jarvis utility.
#
# @description The task installs the link:https://github.com/sebastian-sommerfeld-io/jarvis[Jarvis]
# utility.

- name: Config -> Install jarvis from bootstrap script
  ansible.builtin.shell: |
    set -o pipefail
    whoami
    curl https://raw.githubusercontent.com/sebastian-sommerfeld-io/jarvis/main/src/main/install.sh | bash -
  args:
    executable: /bin/bash
