---
# @file common-install-packages.yml
# @brief Install basic packages.
#
# @description The task installs basic packages that act as dependencies for other
# packages and some handy utilities.

- name: Install -> Basic packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - ncdu
      - htop
      - git
      - neofetch
      - python3-pip # python package manager
    state: latest
    update_cache: true

- name: Install -> Packages to control Dell monitors
  ansible.builtin.apt:
    pkg:
      - ddcui
      - libddcutil4
      - ddcutil
      - i2c-tools
      - libi2c0
      - libx86-1
      - read-edid
    state: latest
    update_cache: true
