---
# @file config-cron-jobs.yml
# @brief Lorem Ipsum ...
#
# @description Lorem Ipsum ...
# TODO ...

- name: Config -> Cron Job "cleanup-filesystem"
  ansible.builtin.cron:
    name: cleanup-filesystem
    # https://crontab.guru/#0_*_*_*_*
    minute: "0"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/home/{{ ansible_user }}/work/repos/sebastian-sommerfeld-io/configs/src/main/homelab/ansible/assets/scripts/cron/cleanup-filesystem.sh"
