---
# @file config-bash-aliases-x86-ubuntu-desktop.yml
# @brief Add aliases to the bash config
#
# @description The task adds aliases to the bash config.
#
# CAUTION: This task is specific to Ubuntu Desktop machines and should not run
# on RasPi nodes or headless nodes.

- name: Config -> Write aliases to .bashrc (for Ubuntu desktop)
  lineinfile:
    create: true
    mode: 0600
    dest: "/home/{{ ansible_user }}/.bash_aliases"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    line: "{{ item }}"
    state: present
  with_items:
    - "alias reset-conky=\"(killall conky && cd /home/{{ ansible_user }}/work/repos/sebastian-sommerfeld-io/configs/src/main/homelab/conky && ./run.sh)\""
