---
- name: Config -> Copy docker wrapper scipts configuration
  ansible.builtin.copy:
    src: "../assets/scripts/docker/wrappers/{{ item }}.sh"
    dest: "/home/{{ ansible_user }}/work/scripts/docker-wrappers/{{ item }}.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=rx,o=rx
  with_items:
    - groovy
    - hadolint
    - hugo
    - mvn
    - node-npm
    - python
    - shellcheck
    - yamllint

- name: Config -> Create symlinks to docker wrapper scipts in /usr/bin
  ansible.builtin.file:
    src: "/home/{{ ansible_user }}/work/scripts/docker-wrappers/{{ item }}.sh"
    dest: "/usr/bin/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  with_items:
    - groovy
    - hadolint
    - hugo
    - mvn
    - python
    - shellcheck
    - yamllint

- name: Config -> Create symlinks to docker wrapper scipt 'node-npm.sh' in /usr/bin
  ansible.builtin.file:
    src: "/home/{{ ansible_user }}/work/scripts/docker-wrappers/node-npm.sh"
    dest: "/usr/bin/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  with_items:
    - node
    - npm
