---
# @file ubuntu-install-ansible.yml
# @brief Install Ansible.
#
# @description The task installs Ansible.

- name: Ansible Setup -> Install ansible (OS-codename {{ ansible_distribution_release }})
  ansible.builtin.apt:
    name:
      - ansible
    state: latest
    update_cache: true
