---
# @file ubuntu-desktop-install-snap-packages.yml
# @brief Install some span packages.
#
# @description The task installs several snap packages (some of them in ``classic`` mode).

- name: Install -> Snap packages
  community.general.snap:
    name:
      - postman
    state: present

- name: Install -> Snap packages (classic)
  community.general.snap:
    name:
      - code # vscode
    state: present
    classic: true
