---
- name: Config -> Write aliases to .bashrc (for Ubuntu desktop)
  lineinfile:
    dest: "/home/{{ ansible_user }}/.bashrc"
    state: present
    line: "{{ item }}"
  with_items:
    - "alias reset-conky=\"(killall conky && cd /home/{{ ansible_user }}/work/repos/sebastian-sommerfeld-io/configs/src/main/conky && ./run.sh)\""
