---
all:
  children:
    x86_ubuntu:
      hosts:
        caprica.fritz.box:
        kobol.fritz.box:
      vars:
        ansible_user: sebastian
        ps1: '${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1) $ '
    raspi:
      hosts:
        prometheus.fritz.box:
        kobol.fritz.box: # todo remove
        caprica.fritz.box: # todo remove
      vars:
        ansible_user: pi
        ps1: '${debian_chroot:+($debian_chroot)}\[\033[01;36m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1) $ '
