---
name: Build + Deployment Pipeline

on:
  push:
    branches-ignore:
      - dependabot/**
    paths-ignore:
      - '**.adoc'
      - '.vscode/**'
  schedule:
    - cron: '0 2 * * 1' # https://crontab.guru/#0_2_*_*_1

permissions:
  contents: read

jobs:
  # ----- Commit stage - 1 - lint ---------------

  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run yamllint
        run: docker compose up lint-yaml --exit-code-from lint-yaml
        shell: bash

  lint-filenames:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ls-lint in container
        run: docker compose up lint-filenames --exit-code-from lint-filenames
        shell: bash

  lint-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run folderslint in container
        run: docker compose up lint-folders --exit-code-from lint-folders
        shell: bash

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          ignore_paths: node_modules target

  lint-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: ansible-lint
        run: |
          (
            cd components/homelab/src/test || exit
            ./lint-ansible.sh
          )
        shell: bash

  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: helm-lint
        run: |
          (
            cd components/homelab/src/test || exit
            ./lint-helm.sh
          )
        shell: bash

  validate-inspec-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Validate inspec profile
        run: docker run --rm --volume ./components/homelab/src/test/inspec:/inspec --workdir /inspec chef/inspec:5.22.36 check homelab-baseline --chef-license=accept-no-persist
        shell: bash

  # ----- Build stage - docs --------------------

  docs:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
      - name: Adjust version in docs/antora.yml
        uses: sebastian-sommerfeld-io/github-action-update-antora-yml@main
        with:
          git_ref: ${{github.ref}}
          file: docs/antora.yml
      - name: Copy adoc files to project root
        run: |
          cp docs/modules/ROOT/pages/index.adoc README.adoc
          cp docs/modules/ROOT/pages/license.adoc LICENSE.adoc
        shell: bash
      - name: Add do-not-edit remark to adoc files in project root
        run: |
          for file in *.adoc; do

            {
              echo
              echo "// +---------------------------------------------------+"
              echo "// |                                                   |"
              echo "// |        DO NOT EDIT DIRECTLY !!!!!                 |"
              echo "// |                                                   |"
              echo "// |        File is auto-generated by pipeline.        |"
              echo "// |        Contents are based on Antora docs.         |"
              echo "// |                                                   |"
              echo "// +---------------------------------------------------+"
            } >> "$file"

          done
        shell: bash
      - name: Replace xref with links to GitHub in adoc files in project root
        run: |
          for file in *.adoc; do
            content=$(cat "$file")
            content="${content//xref:AUTO-GENERATED:bash-docs/index.adoc[]/link:https://github.com/sebastian-sommerfeld-io/configs/tree/main/docs/modules/AUTO-GENERATED/pages/components/homelab/src/main[the inline docs]}"
            echo "$content" > "$file"
          done
        shell: bash
      - name: Copy partials from Helm carts
        run: |
          readonly PARTIAL_DIR="docs/modules/AUTO-GENERATED/partials/helm-charts"
          mkdir -p "$PARTIAL_DIR"
          cp components/homelab/src/main/minikube/krokidile-chart/krokidile/README.adoc "$PARTIAL_DIR/krokidile.adoc"
          cp components/homelab/src/main/minikube/source2adoc-chart/source2adoc-website/README.adoc "$PARTIAL_DIR/source2adoc-website.adoc"
        shell: bash
      - name: Commit and push
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: sebastian
          author_email: sebastian@sommerfeld.io
          message: 'docs: [Actions Bot] generate docs'

  # ----- Tag repository ------------------------

  release-code:
    runs-on: ubuntu-latest
    needs: ['docs']
    if: ${{ (github.actor != 'dependabot[bot]') && (github.ref == 'refs/heads/main') }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
      - name: Info - docs/antora.yml
        run: cat docs/antora.yml
        shell: bash
      - name: Install Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 22.2.0
      - name: semantic-release - Install
        run: |
          npm install --save-dev semantic-release
          npm install --save-dev @semantic-release/commit-analyzer
          npm install --save-dev @semantic-release/release-notes-generator
          npm install --save-dev @semantic-release/npm
          npm install --save-dev @semantic-release/exec
          npm install --save-dev @semantic-release/git
          npm install --save-dev @semantic-release/github
        shell: bash
      # TODO bump versions in antora.yml + push
      # TODO https://github.com/sommerfeld-io/krokidile/issues/20
      - name: semantic-release - Run
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_REPO_AND_PROJECT }}
        run: npx semantic-release
        shell: bash
      - name: Info - docs/antora.yml
        run: cat docs/antora.yml
        shell: bash
      # TODO revert version in antora.yml? from bash (sed)?
      # TODO https://github.com/sommerfeld-io/krokidile/issues/20
      - name: Commit and push
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: sebastian
          author_email: sebastian@sommerfeld.io
          message: 'docs: [Actions Bot] bump version'
      - name: Reset version in docs/antora.yml (back to branch name)
        uses: sebastian-sommerfeld-io/github-action-update-antora-yml@main
        with:
          git_ref: ${{github.ref}}
          file: docs/antora.yml
      - name: Commit and push
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: sebastian
          author_email: sebastian@sommerfeld.io
          message: 'docs: [Actions Bot] reset version back to branch name'
