---
# @file docker-compose.yml
# @brief Run portainer with a default configuration.
#
# @description This ``portainer`` miminal Docker stack starts a link:https://github.com/portainer/portainer[Portainer CE]
# instance. This link:https://docs.portainer.io[Portainer] instance is pre-configured with an
# admin user but does not come with any additional config.
#
# | Component     | Port | URL                   |
# | ------------- | ---- | --------------------- |
# | Portainer     | 9990 | http://localhost:9990 |

services:

  portainer-min:
    image: portainer/portainer-ce:2.19.4-alpine
    container_name: portainer-min
    command: --host unix:///var/run/docker.sock --admin-password-file /tmp/portainer_passwords
    restart: always
    ports:
      - 9990:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - ./assets/portainer.passwd:/tmp/portainer_passwords
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:9000 || exit 1"
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 10s

volumes:
  portainer_data:
